import { ArrowUpRight, Hospital, MapPin, Search, Video } from 'lucide-react'
import { useState } from 'react'
import { facilities } from '../components/data'

export default function FacilitiesPage() {
	const [search, setSearch] = useState('')
	const filteredFacilities = facilities.filter((facility) => `${facility.name} ${facility.type} ${facility.location}`.toLowerCase().includes(search.toLowerCase()))

	return <div className="page-wrap"><section className="welcome-row"><div><p className="eyebrow">FACILITY DISCOVERY <span>•</span> BHOPAL, MP</p><h1>Find care nearby</h1><p className="subheading">Locate PHCs, CHCs, and government hospitals across Bhopal.</p></div><button className="primary-button" onClick={() => window.alert('Location access requested.')}><MapPin size={18} /> Use my location</button></section><div className="facility-search"><Search size={18} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search facility, type, or locality" aria-label="Search Bhopal facilities" /><button onClick={() => setSearch(search.trim())}>Search</button></div><div className="facility-list">{filteredFacilities.map((facility) => <div className="facility-card" key={facility.name}><div className="facility-icon"><Hospital size={22} /></div><div className="facility-main"><div className="facility-title"><h2>{facility.name}</h2><span className={`status-pill ${facility.tone}`}><i />{facility.availability}</span></div><p>{facility.type} <span>•</span> {facility.location} <span>•</span> {facility.distance} away</p><div className="facility-actions"><button onClick={() => window.alert(`Directions to ${facility.name}`)}><MapPin size={14} /> Directions</button><button onClick={() => window.alert(`Teleconsultation request sent to ${facility.name}`)}><Video size={14} /> Teleconsult</button><button className="icon-button" aria-label="Open facility" onClick={() => window.alert(`Opening ${facility.name}`)}><ArrowUpRight size={17} /></button></div></div></div>)}{filteredFacilities.length === 0 && <div className="empty-page"><h2>No facilities found</h2><p>Try searching for a Bhopal hospital, CHC, or PHC.</p></div>}</div></div>
}
