import { Activity, ChevronRight, ClipboardList, HeartPulse, MessageCircle, ShieldCheck, Stethoscope, TrendingUp, Users } from 'lucide-react'
import { Link, useNavigate, useOutletContext } from 'react-router-dom'
import { patients } from '../components/data'
import PatientTable from '../components/PatientTable'
import QuickActions from '../components/QuickActions'

export default function OverviewPage() {
  const { openRegistration } = useOutletContext()
  const navigate = useNavigate()
  return <div className="page-wrap"><section className="welcome-row"><div><p className="eyebrow">TUESDAY, 08 SEPTEMBER 2026 <span>•</span> BHAGWANPUR BLOCK</p><h1>Good morning, Anjali <span>↗</span></h1><p className="subheading">Here is what needs your attention today.</p></div><button className="primary-button" onClick={openRegistration}><HeartPulse size={18} /> Register patient</button></section><StatCards /><section className="content-grid"><div className="primary-column"><div className="section-heading"><div><h2>Today&apos;s patient queue</h2><p>Recent registrations and follow-ups</p></div><Link className="text-button" to="/patients">View all patients <ChevronRight size={15} /></Link></div><PatientTable patients={patients} compact onViewAll={() => navigate('/patients')} /></div><aside className="right-column"><div className="section-heading"><div><h2>Quick actions</h2><p>Common tasks, one tap away</p></div></div><QuickActions onNewPatient={openRegistration} /><ReferralOverview /></aside></section><section className="bottom-banner"><div className="banner-icon"><MessageCircle size={22} /></div><div><strong>Need help with a patient?</strong><span>Connect with a doctor or specialist for guidance.</span></div><Link className="outline-button" to="/facilities"><Stethoscope size={16} /> Start teleconsultation</Link></section></div>
}

function StatCards() { return <section className="stat-grid" aria-label="Today's overview"><div className="stat-card stat-warm"><div className="stat-icon"><Users size={19} /></div><span className="stat-label">Patients today</span><strong>24</strong><small><b>+6</b> from yesterday</small><div className="sparkline"><i /><i /><i /><i /><i /><i /><i /></div></div><div className="stat-card stat-rose"><div className="stat-icon"><Activity size={19} /></div><span className="stat-label">Need attention</span><strong>08</strong><small className="warning-text"><b>3 urgent</b> cases today</small><div className="risk-bars"><i /><i /><i /><i /><i /><i /><i /><i /></div></div><div className="stat-card stat-sand"><div className="stat-icon"><ClipboardList size={19} /></div><span className="stat-label">Active referrals</span><strong>12</strong><small><b>4</b> awaiting action</small><div className="progress-line"><span /></div></div><div className="stat-card stat-mint"><div className="stat-icon"><ShieldCheck size={19} /></div><span className="stat-label">Follow-ups due</span><strong>06</strong><small><b>2</b> due this week</small><div className="mini-avatars"><span className="avatar avatar-coral">MD</span><span className="avatar avatar-blue">RK</span><span className="avatar avatar-gold">+4</span></div></div></section> }

function ReferralOverview() { return <><div className="section-heading referral-heading"><div><h2>Referral overview</h2><p>Current month</p></div><button className="icon-button" onClick={() => window.alert('Referral summary: 18 completed, 9 in progress, 5 pending.')}><TrendingUp size={19} /></button></div><div className="referral-card"><div className="donut-wrap"><div className="donut"><div><strong>32</strong><small>Total</small></div></div></div><div className="referral-legend"><p><i className="legend-dot completed" />Completed <strong>18</strong></p><p><i className="legend-dot progress" />In progress <strong>09</strong></p><p><i className="legend-dot pending" />Pending <strong>05</strong></p></div><div className="referral-foot"><span><TrendingUp size={14} /> 12% from last month</span><Link to="/referrals">Details <ChevronRight size={14} /></Link></div></div></> }
