import { ArrowUpRight, Check, ClipboardList, MapPin, Plus } from 'lucide-react'
import { Link } from 'react-router-dom'

const referrals = [{ patient: 'Meena Devi', destination: 'District Hospital', status: 'Urgent', tone: 'risk' }, { patient: 'Ramesh Kumar', destination: 'Bhagwanpur PHC', status: 'In progress', tone: 'follow' }, { patient: 'Kavita Sharma', destination: 'Women & Child Centre', status: 'Pending', tone: 'stable' }]

export default function ReferralsPage() {
  return <div className="page-wrap"><section className="welcome-row"><div><p className="eyebrow">CARE COORDINATION <span>•</span> 12 ACTIVE</p><h1>Referral tracking</h1><p className="subheading">Keep every patient moving to the care they need.</p></div><button className="primary-button" onClick={() => window.alert('Referral form opened. Connect this action to your referral API.')}><Plus size={18} /> Create referral</button></section><div className="referral-summary-grid"><Summary icon={ClipboardList} label="Total this month" value="32" /><Summary icon={Check} label="Completed" value="18" /><Summary icon={ArrowUpRight} label="Needs action" value="09" /></div><div className="section-heading"><div><h2>Active referrals</h2><p>Latest referrals from your workspace</p></div><Link className="text-button" to="/facilities">Browse facilities <MapPin size={14} /></Link></div><div className="referral-list">{referrals.map((referral) => <div className="referral-list-row" key={referral.patient}><div className="avatar avatar-coral">{referral.patient.split(' ').map((part) => part[0]).join('')}</div><div><strong>{referral.patient}</strong><span>{referral.destination}</span></div><span className={`status-pill ${referral.tone}`}><i />{referral.status}</span><button className="text-button" onClick={() => window.alert(`Opening referral for ${referral.patient}`)}>Open <ArrowUpRight size={14} /></button></div>)}</div></div>
}
function Summary({ icon: Icon, label, value }) { return <div className="stat-card stat-sand referral-summary"><div className="stat-icon"><Icon size={19} /></div><span className="stat-label">{label}</span><strong>{value}</strong></div> }
